services:
    kasimi.postnumbers.listener:
        class: 'kasimi\postnumbers\event\listener'
        arguments:
            - '@user'
            - '@language'
            - '@config'
            - '@request'
            - '@template'
            - '@ext.manager'
            - '@dbal.conn'
            - '@?rxu.FirstPostOnEveryPage.listener'
            - '@?Aurelienazerty.DisplayLastPost.listener'
        tags:
            - { name: 'event.listener' }

    kasimi.postnumbers.controller.acp:
        class: 'kasimi\postnumbers\controller\acp'
        arguments:
            - '@user'
            - '@language'
            - '@config'
            - '@request'
            - '@template'
            - '@log'
